### ISSUE TITLE
Not able to build spookystuff with shell scripts

### ISSUE THREAD

**Issue by etmjansen** [tribbloid/spookystuff#37]
Whether I am running maven-install.sh or test-install.sh I am getting the following error:

```
Failed to execute goal on project spookystuff-shell: Could not resolve dependencies for project org.tribbloid.spookystuff:spookystuff-shell:jar:0.3.0-SNAPSHOT: Failure to find org.apache.spark:spark-repl_2.10:jar:1.2.0 in https://repo.typesafe.com/typesafe/releases was cached in the local repository, resolution will not be reattempted until the update interval of typesafe has elapsed or updates are forced -> [Help 1]
```

I put the following entry in my maven settings.xml.

```
 <repository>
        <id>typesafe</id>
        <name>typesafe-releases</name>
        <url>https://repo.typesafe.com/typesafe/releases</url>
 </repository>
```

The only maven repository reference I could find online were references to a spark_repl_2.1.0:1.2.0-SNAPSHOT... I can not find any artifacts for a released spark_repl_2.1.0:1.2.0 version.

**Comment by l2yao** [comment]
Hi etmjansen,

For temporary walk around, you can set ${spark.version} to 1.1.0 spark-repl dependency. then u should be able to build.
Or you can wait till 1.2.0 is updated on mvn central repo, then everything should work as it is.

**Comment by etmjansen** [comment]
Thank you all for the comments. I got it working by applying the path.

**Comment by tribbloid** [comment]
ok 1.2.1 is released you no longer need the patch
