### ISSUE TITLE
Documentation: Section on Usage regarding Context

### ISSUE THREAD

**Issue by RAbraham** [tribbloid/spookystuff#38]
Hi,
In the section Usage, regarding Context, the following code example is given
''
Creating of Context can use any Spark parallelization or transformation (though this is rarely used), e.g.:

- sc.parallelize("Metallica","Megadeth","Slayer","Anthrax")
''

As expected, this gives an error.

Should it be sc.parallelize(Seq(...))

**Comment by tribbloid** [comment]
Yeah you are right, sorry about that.
Documentations will be gradually moved to Wiki.

**Comment by RAbraham** [comment]
Hi Peng,
Does this Wiki already exist or you have to create one? If it already
exists, can you paste the link?



2015-01-05 14:31 GMT-05:00 Peng Cheng <notifications@github.com>:

> Yeah you are right, sorry about that.
> Documentations will be gradually moved to Wiki.
>
> On 01/05/2015 11:33 AM, Rajiv Abraham wrote:
> >
> > Hi,
> > In the section Usage, regarding Context, the following code example is
> > given
> > ''
> > Creating of Context can use any Spark parallelization or
> > transformation (though this is rarely used), e.g.:
> >
> > * sc.parallelize("Metallica","Megadeth","Slayer","Anthrax") ''
> >
> > As expected, this gives an error.
> >
> > Should it be sc.parallelize(Seq(...))
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/tribbloid/spookystuff/issues/38>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tribbloid/spookystuff/issues/38#issuecomment-68762145>
> .
>



-- 
Take care,
Rajiv

**Comment by l2yao** [comment]
I believe this is the wiki page: https://github.com/tribbloid/spookystuff/wiki

**Comment by RAbraham** [comment]
Thanks Long :).
