### ISSUE TITLE
Downloads on github.io page don't work and SBT can't find SpookyStuff in Maven

### ISSUE THREAD

**Issue by austinprete** [tribbloid/spookystuff#44]
I recently downloaded version 0.3.0 of SpookyStuff and noticed a new stable release was documented yesterday on tribbloid.github.io . However, the links to download the .jar are not working and adding the SBT dependency also fails.

**Comment by tribbloid** [comment]
Sorry it wasn't released, the doc was kind of not synched properly, will 
be fixed in 24 hours

**Comment by tribbloid** [comment]
working right now, case closed
