### ISSUE TITLE
Link Extractors

### ISSUE THREAD

**Issue by austinprete** [tribbloid/spookystuff#47]
Scrapy implements a notion of a link extractor which serves the purpose of easily extracting links from a web page. Those links can subsequently be followed by the crawler to discover more content. (http://doc.scrapy.org/en/1.0/topics/link-extractors.html) I'd like to implement something similar in SpookyStuff assuming this is something that people would find valuable. (I believe it is) On a similar note, I'd also like to work on other "extractors" such as ones that extract phone numbers or emails from a crawled web page.

**Comment by tribbloid** [comment]
can you just use S"*[href]" expression? As a short example:

class BlogSpider(scrapy.Spider):
    name = 'blogspider'
    start_urls = ['http://blog.scrapinghub.com']

    def parse(self, response):
        for url in response.css('ul li a::attr("href")').re(r'.*/\d\d\d\d/\d\d/$'):
            yield scrapy.Request(response.urljoin(url), self.parse_titles)

    def parse_titles(self, response):
        for post_title in response.css('div.entries > ul > li a::text').extract():
            yield {'title': post_title}

is equivalent to:

spooky.wget("http://blog.scrapinghub.com"
).explore( S"ul li a"
	filterByRefex ".*//\d\d\d\d//\d\d//$" )(
	Wget('A.href)
)(
	S"div.entries > ul > li a".text ~ 'title
).toDF()

in spookystuff

**Comment by austinprete** [comment]
Oh, I suppose that works just as well! I'll close out the issue.
